import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { hash } from "./utils.mjs";
import { validateInventory } from "./schemas.mjs";
import { loadConfig } from "./config.mjs";
function frontmatter(source) { const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/); if (!match) throw new Error("article frontmatter is missing."); const data = {}; for (const line of match[1].split(/\r?\n/)) { const item = line.match(/^(\w+):\s*(.*)$/); if (item) data[item[1]] = item[2].replace(/^"|"$/g, ""); } return { data, body: match[2] }; }
const list = (value) => (value?.match(/\[([^\]]*)\]/)?.[1] ?? "").split(",").map((item) => item.trim()).filter(Boolean);
export const deriveRoute = (slug) => `/en/blog/${slug}/`;
export async function buildInventory({ rootDir, includeDrafts = true }) { const { brand } = await loadConfig(rootDir); const directory = path.join(rootDir, "src", "content", "blog"); const names = (await readdir(directory)).filter((name) => name.endsWith(".md")).sort((a, b) => a.localeCompare(b)); const articles = []; for (const name of names) { const slug = path.basename(name, ".md"); const source = await readFile(path.join(directory, name), "utf8"); const { data, body } = frontmatter(source); const draft = data.draft === "true"; if (!includeDrafts && draft) continue; const candidateDirectories = [slug, brand.researchDirectoryAliases?.[slug]].filter(Boolean); let relatedResearchDirectory = null; for (const candidate of candidateDirectories) try { await readdir(path.join(rootDir, "docs", "research", "blog", candidate)); relatedResearchDirectory = `docs/research/blog/${candidate}`; break; } catch {} const internalLinks = [...body.matchAll(/\]\((\/en\/[^)]+)\)/g)].map((match) => match[1]).sort(); const entities = (brand.entityVocabulary ?? []).filter((entity) => new RegExp(`\\b${entity}\\b`, "i").test(`${data.title ?? ""} ${body}`)); const keywords = [...new Set([...(data.tags ? list(data.tags) : []), ...entities.map((entity) => entity.toLowerCase())])].sort(); articles.push({ slug, title: data.title, description: data.description ?? data.subtitle ?? "", pubDate: data.pubDate, draft, category: data.category ?? null, region: data.region ?? null, tags: list(data.tags), route: deriveRoute(slug), image: data.image ?? null, imageCredit: data.imageCredit ?? null, headings: [...body.matchAll(/^##\s+(.+)$/gm)].map((match) => match[1]), wordCount: (body.match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu) ?? []).length, internalLinks, entities, keywords, relatedResearchDirectory, videoReadiness: draft ? "draft review required" : "human review required", sourceFingerprint: hash(source) }); } return validateInventory({ schemaVersion: 3, generatedAt: "deterministic", includeDrafts, articles }); }
export function inventoryMarkdown(inventory) { return `# Content inventory\n\n| Title | Draft | Route | Words | Video readiness |\n| --- | --- | ---: | ---: | --- |\n${inventory.articles.map((article) => `| ${article.title} | ${article.draft ? "yes" : "no"} | ${article.route} | ${article.wordCount} | ${article.videoReadiness} |`).join("\n")}\n`; }
export { frontmatter };
